---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
editor_options:
  chunk_output_type: console
---

\renewcommand{\[}{\begin{equation}}
\renewcommand{\]}{\end{equation}}


```{r, warning=FALSE, message=FALSE}
library(conflicted)
library(eurostat)
library(gets)
library(tidyverse)
library(janitor)
library(kableExtra)
library(plotly)
library(here)
library(lubridate)
library(fastDummies)


conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("as.zoo.data.frame", "zoo")
conflict_prefer("select", "dplyr")
options(bitmapType = 'cairo') # for ggplotly
```


# Input

```{r}
overall <- read_csv(here("data/raw/eurostat_download.csv"))
unit_choice <- "Current prices, million euro" #CHECKAGAIN
s_adj_choice <- "Unadjusted data (i.e. neither seasonally adjusted nor calendar adjusted data)" #CHECKAGAIN

cp_estimated <- read_csv(here("data/temp/cp.csv"))
```

$$Gross capital formation $$



```{r}
#CHECKAGAIN whether to model Imports as a Function of Exports. NAM does, we currently don't
overall %>% 
  filter(na_item %in% c(
    "Imports of goods and services",
    "Gross capital formation",
    #"Adjusted disposable income, gross"
    NULL
  )) %>% 
  filter(unit == unit_choice) %>% 
  filter(s_adj == s_adj_choice) %>% 
  filter(na_item == "Imports of goods and services" | sector == "Total economy") %>%  #CHECKAGAIN
  filter(is.na(direct) | direct != "Received") %>% 
  filter(is.na(sector) | sector == "Total economy") %>% #CHECKAGAIN
  
  select(-direct,-sector) %>% 
  janitor::remove_empty(which = "cols") %>% 
  distinct -> imports_data

```



```{r}
max.lag <- 4
saturation.tpval <- 0.01
```


```{r}
imports_data %>% 
  select(na_item, time,values) %>%
  pivot_wider(id_cols = time, names_from = na_item, values_from = values) %>% 
  clean_names() %>% 
  
  # Add previously estimated data
  full_join(cp_estimated %>% select(-index), by = "time") %>% 
  
  arrange(time) %>% 
  mutate(across(-time,list(L = log),.names = "{.fn}.{.col}"),
         across(starts_with("L."),list(D = ~c(NA,diff(., ))), .names = "{.fn}{.col}"),
         
         # ECM
         across(starts_with("L."),list(L = lag),.names = "{.fn}1.{.col}"),
         index = 1:n()) %>% 
  relocate(index) %>% 
  mutate(q = quarter(time, with_year = FALSE)) %>% 
  dummy_cols(select_columns = "q", remove_first_dummy = TRUE, remove_selected_columns = TRUE) -> imports_data_clean
```





## Imports

```{r}
isat_list <- tibble(ar = 0:4,
                    BIC = 0,
                    isat_object = list(NA_complex_))
for(i in 0:4){
  intermed.model <- isat(
    imports_data_clean$DL.imports_of_goods_and_services,
    mxreg = imports_data_clean %>% 
      select(cp.fitted.level, DL.gross_capital_formation,
             q_2,q_3,q_4), 
    ar = if (i != 0) {1:i} else{NULL},
    plot = FALSE,
    print.searchinfo = FALSE,
    iis = TRUE,
    sis = TRUE,
    t.pval = saturation.tpval
  )
  
  isat_list[i + 1,"BIC"] <- BIC(intermed.model)
  isat_list[i + 1,"isat_object"] <- tibble(isat_object = list(intermed.model))
  
}
```


```{r}
isat_list %>% 
  filter(BIC == min(BIC)) %>% 
  pull(isat_object) %>% first -> imports.model

plot(imports.model)
```


# Putting them back together

```{r, eval = FALSE}
add_to_original_data <- function(){
  
  
  
  
}
```




```{r}
# imports_data_clean$imports.fitted <- NA
# imports_data_clean$imports.fitted[imports.model$aux$y.index] <- as.numeric(imports.model$mean.fit)
# 
# 

imports_data_clean %>% 
  
  full_join(tibble(index = imports.model$aux$y.index, 
                   imports.fitted = as.numeric(imports.model$mean.fit)), by = "index") %>% 

mutate(imports.fitted.cumsum = case_when(is.na(imports.fitted) & is.na(lead(imports.fitted))~0,
                                       is.na(imports.fitted) & !is.na(lead(imports.fitted))~L.imports_of_goods_and_services,
                                       !is.na(imports.fitted) ~ imports.fitted),
       imports.fitted.cumsum = cumsum(imports.fitted.cumsum),
       imports.fitted.cumsum = ifelse(is.na(imports.fitted),NA,imports.fitted.cumsum)) %>% 
  
  
  mutate(imports.fitted.level = exp(imports.fitted.cumsum)) -> df_done
```


```{r}
df_done %>% 
  ggplot(aes(x = time)) + 
  geom_line(aes(y = imports_of_goods_and_services), col = "blue") + 
  
  
  geom_line(aes(y = imports.fitted.level), col = "red", linetype = 2) + 
  
  theme_minimal()

```

```{r}
write_csv(df_done %>% select(index, time, household_and_npish_final_consumption_expenditure, imports.fitted.level), here("data/temp/imports.csv"))
```

