---
title: "R Notebook"
output: 
  bookdown::html_document2: 
    theme: "lumen"
    code_download: true
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    df_print: paged
knit: (function(inputFile, encoding) { 
  rmarkdown::render(inputFile, 
  encoding = encoding, 
  output_format = "html_document", 
  output_dir = here::here("output")) 
  })
editor_options:
  chunk_output_type: console
---

<!-- For equations: \begin{equation} \end{equation} and then add (\#eq:XXX) just before the end -->


# Set-up
  
```{r, echo=FALSE}
knitr::opts_chunk$set(comment = NA, echo = TRUE, eval = TRUE, 
                      warning = FALSE, message = FALSE, 
                      fig.width = 6, fig.height = 4)
```



```{r, warning=FALSE, message=FALSE}
library(conflicted)
library(eurostat)
library(gets)
library(tidyverse)
library(janitor)
library(kableExtra)
library(plotly)
library(here)
library(lubridate)
library(fastDummies)


conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("as.zoo.data.frame", "zoo")
conflict_prefer("select", "dplyr")
options(bitmapType = 'cairo') # for ggplotly
```


# Input

```{r}
overall <- read_csv(here("data/raw/eurostat_download.csv"))
unit_choice <- "Current prices, million euro" #CHECKAGAIN
s_adj_choice <- "Unadjusted data (i.e. neither seasonally adjusted nor calendar adjusted data)" #CHECKAGAIN

source(here("code/modelling_functions.R"))

ardl_ecm_opts <- "ardl"
saturation.tpval <- 0.01
max.lag <- 4

cp_estimated <- read_csv(here("data/temp/cp.csv"))
```





```{r}
#CHECKAGAIN whether to model Imports as a Function of Exports. NAM does, we currently don't
overall %>% 
  filter(na_item %in% c(
    "Imports of goods and services",
    "Gross capital formation",
    #"Adjusted disposable income, gross"
    NULL
  )) %>% 
  filter(unit == unit_choice) %>% 
  filter(s_adj == s_adj_choice) %>% 
  filter(na_item == "Imports of goods and services" | sector == "Total economy") %>%  #CHECKAGAIN
  filter(is.na(direct) | direct != "Received") %>% 
  filter(is.na(sector) | sector == "Total economy") %>% #CHECKAGAIN
  
  select(-direct,-sector) %>% 
  janitor::remove_empty(which = "cols") %>% 
  distinct -> imports_data

```





```{r}
imports_data %>% 
  select(na_item, time,values) %>%
  pivot_wider(id_cols = time, names_from = na_item, values_from = values) %>% 
  clean_names() %>% 
  
  # Add previously estimated data
  full_join(cp_estimated %>% select(-index), by = "time") %>% 
  
  arrange(time) %>% 
  mutate(across(-time,list(ln = log),.names = "{.fn}.{.col}"),
         across(starts_with("ln."),list(D = ~c(NA,diff(., ))), .names = "{.fn}.{.col}"),
         
         # ECM
         across(c(starts_with("D."),starts_with("ln.")),list(L = lag),.names = "{.fn}1.{.col}"),
         across(c(starts_with("D."),starts_with("ln.")),list(L = ~lag(.,2)),.names = "{.fn}2.{.col}"),
         across(c(starts_with("D."),starts_with("ln.")),list(L = ~lag(.,3)),.names = "{.fn}3.{.col}"),
         across(c(starts_with("D."),starts_with("ln.")),list(L = ~lag(.,4)),.names = "{.fn}4.{.col}"),
         index = 1:n()) %>% 
  relocate(index) %>% 
  mutate(q = quarter(time, with_year = FALSE)) %>% 
  dummy_cols(select_columns = "q", remove_first_dummy = TRUE, remove_selected_columns = TRUE) -> imports_data_clean
```





## Imports

```{r}
done_isat_modelling <- isat_modelling(clean_data = imports_data_clean, 
                                      dep_var_basename = "imports_of_goods_and_services",
                                      ardl_or_ecm = "ecm")

done_isat_modelling2 <- isat_modelling(clean_data = imports_data_clean, 
                                      dep_var_basename = "imports_of_goods_and_services",
                                      ardl_or_ecm = "ardl")

# for(i in 0:4){
#   intermed.model <- isat(
#     imports_data_clean$DL.imports_of_goods_and_services,
#     mxreg = imports_data_clean %>% 
#       select(cp.fitted.level, DL.gross_capital_formation,
#              q_2,q_3,q_4), 
#     ar = if (i != 0) {1:i} else{NULL},
#     plot = FALSE,
#     print.searchinfo = FALSE,
#     iis = TRUE,
#     sis = TRUE,
#     t.pval = saturation.tpval
#   )
#   
#   isat_list[i + 1,"BIC"] <- BIC(intermed.model)
#   isat_list[i + 1,"isat_object"] <- tibble(isat_object = list(intermed.model))
#   
# }



```


```{r, eval = FALSE}
isat_list <- tibble(ar = 0:4,
                    BIC = 0,
                    isat_object = list(NA_complex_))
for(i in 0:4){
  xvars <- grep("gross_capital",grep("L[0-9]\\.",names(imports_data_clean), value = TRUE), value = TRUE)
  
  intermed.model <- isat(
    imports_data_clean$L.imports_of_goods_and_services,
    mxreg = imports_data_clean %>% 
      select(household_and_npish_final_consumption_expenditure, L.gross_capital_formation,
             if(i != 0){all_of(xvars[1:i])}else{NULL},
             q_2,q_3,q_4), 
    ar = if (i != 0) {1:i} else{NULL},
    plot = FALSE,
    print.searchinfo = FALSE,
    iis = TRUE,
    sis = TRUE,
    t.pval = saturation.tpval
  )
  
  isat_list[i + 1,"BIC"] <- BIC(intermed.model)
  isat_list[i + 1,"isat_object"] <- tibble(isat_object = list(intermed.model))
  
}

# for(i in 0:4){
#   intermed.model <- isat(
#     imports_data_clean$DL.imports_of_goods_and_services,
#     mxreg = imports_data_clean %>% 
#       select(cp.fitted.level, DL.gross_capital_formation,
#              q_2,q_3,q_4), 
#     ar = if (i != 0) {1:i} else{NULL},
#     plot = FALSE,
#     print.searchinfo = FALSE,
#     iis = TRUE,
#     sis = TRUE,
#     t.pval = saturation.tpval
#   )
#   
#   isat_list[i + 1,"BIC"] <- BIC(intermed.model)
#   isat_list[i + 1,"isat_object"] <- tibble(isat_object = list(intermed.model))
#   
# }



```


```{r, eval = TRUE}
plot(done_isat_modelling$best_model)
```


# Putting them back together


```{r}
df_done <- add_to_original_data(clean_data = imports_data_clean,
                                isat_object = done_isat_modelling$best_model, 
                                dep_var_name = "imports",
                                ardl_or_ecm = ardl_ecm_opts)
```




```{r,eval = FALSE}
# imports_data_clean$imports.fitted <- NA
# imports_data_clean$imports.fitted[imports.model$aux$y.index] <- as.numeric(imports.model$mean.fit)
# 
# 


imports_data_clean %>% 
  
  full_join(tibble(index = imports.model$aux$y.index, 
                   imports.fitted = as.numeric(imports.model$mean.fit)), by = "index") %>% 
  
  # mutate(imports.fitted.cumsum = case_when(is.na(imports.fitted) & is.na(lead(imports.fitted))~0,
  #                                          is.na(imports.fitted) & !is.na(lead(imports.fitted))~L.imports_of_goods_and_services,
  #                                          !is.na(imports.fitted) ~ imports.fitted),
  #        imports.fitted.cumsum = cumsum(imports.fitted.cumsum),
  #        imports.fitted.cumsum = ifelse(is.na(imports.fitted),NA,imports.fitted.cumsum)) %>% 
  
  
  #mutate(imports.fitted.level = exp(imports.fitted.cumsum)) %>% 
  mutate(imports.fitted.level = exp(imports.fitted)) %>% 
  return() -> df_done



# imports_data_clean %>% 
#   
#   full_join(tibble(index = imports.model$aux$y.index, 
#                    imports.fitted = as.numeric(imports.model$mean.fit)), by = "index") %>% 
# 
# mutate(imports.fitted.cumsum = case_when(is.na(imports.fitted) & is.na(lead(imports.fitted))~0,
#                                        is.na(imports.fitted) & !is.na(lead(imports.fitted))~L.imports_of_goods_and_services,
#                                        !is.na(imports.fitted) ~ imports.fitted),
#        imports.fitted.cumsum = cumsum(imports.fitted.cumsum),
#        imports.fitted.cumsum = ifelse(is.na(imports.fitted),NA,imports.fitted.cumsum)) %>% 
#   
#   
#   mutate(imports.fitted.level = exp(imports.fitted.cumsum)) -> df_done
```


```{r}
df_done %>% 
  ggplot(aes(x = time)) + 
  geom_line(aes(y = imports_of_goods_and_services), col = "blue") + 
  
  geom_line(aes(y = imports.level), col = "red", linetype = 2, size = 1) + 
  theme_minimal()
```

```{r, eval = FALSE}
write_csv(df_done %>% select(index, time, household_and_npish_final_consumption_expenditure, imports.fitted.level), here("data/temp/imports.csv"))
```

