---
title: "R Notebook"
output: 
  bookdown::html_document2: 
    code_download: true
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    df_print: paged
knit: (function(inputFile, encoding) { 
  rmarkdown::render(inputFile, 
  encoding = encoding, 
  output_format = "html_document", 
  output_dir = here::here("output")) 
  })
editor_options:
  chunk_output_type: console
---

<!-- For equations: \begin{equation} \end{equation} and then add (\#eq:XXX) just before the end -->


# Set-up

```{r, echo=FALSE}
knitr::opts_chunk$set(comment = NA, echo = TRUE, eval = TRUE, 
                      warning = FALSE, message = FALSE, 
                      fig.width = 6, fig.height = 4)
```


```{r, warning=FALSE, message=FALSE}
library(conflicted)
library(eurostat)
library(gets)
library(tidyverse)
library(janitor)
library(kableExtra)
library(plotly)
library(here)
library(lubridate)
library(fastDummies)

# 
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("here", "here")
conflict_prefer("as.zoo.data.frame", "zoo")
conflict_prefer("select", "dplyr")
options(bitmapType = 'cairo') # for ggplotly
```

# Input

```{r}
overall <- read_csv(here("data/raw/eurostat_download.csv"))
unit_choice <- "Current prices, million euro" #CHECKAGAIN
s_adj_choice <- "Unadjusted data (i.e. neither seasonally adjusted nor calendar adjusted data)" #CHECKAGAIN
source(here("code/modelling_functions.R"))

ardl_ecm_opts <- "ardl"
saturation.tpval <- 0.01
```


```{r}
#CHECKAGAIN GDP is identified twice in the different datasets. Currently taking an average
overall %>% 
  filter(na_item %in% c(
    "Gross domestic product at market prices",
    
    NULL
  ) | !is.na(airpol)) %>% 
  filter(unit == "Thousand tonnes" | unit == unit_choice) %>% 
  filter(s_adj == s_adj_choice | !is.na(airpol)) %>% 
  
  janitor::remove_empty(which = "cols") %>% 
  mutate(na_item = case_when(is.na(na_item) & airpol == "Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)"~"co2eq",
                             TRUE ~ na_item)) %>% 
  select(-c(nace_r2:airpol)) %>% 
  distinct -> co2data
```






```{r}
co2data %>% 
  select(na_item, time,values) %>%
  #CHECKAGAIN GDP is identified twice in the different datasets. Currently taking an average
  pivot_wider(id_cols = time, names_from = na_item, values_from = values,values_fn = mean) %>% 
  clean_names() %>% 
  
  # Add previously estimated data
  
  
  arrange(time) %>% 
  mutate(across(-time,list(ln = log),.names = "{.fn}.{.col}"),
         across(starts_with("ln."),list(D = ~c(NA,diff(., ))), .names = "{.fn}.{.col}"),
         
         # ECM
         across(c(starts_with("D."),starts_with("ln.")),list(L = lag),.names = "{.fn}1.{.col}"),
         across(c(starts_with("D."),starts_with("ln.")),list(L = ~lag(.,2)),.names = "{.fn}2.{.col}"),
         across(c(starts_with("D."),starts_with("ln.")),list(L = ~lag(.,3)),.names = "{.fn}3.{.col}"),
         across(c(starts_with("D."),starts_with("ln.")),list(L = ~lag(.,4)),.names = "{.fn}4.{.col}"),
         index = 1:n()) %>% 
  relocate(index) %>% 
  mutate(q = quarter(time, with_year = FALSE)) %>% 
  dummy_cols(select_columns = "q", remove_first_dummy = TRUE, remove_selected_columns = TRUE) -> co2data_clean
```



## Imports

```{r}
done_isat_modelling <- isat_modelling(
  clean_data = co2data_clean, 
  dep_var_basename = "co2eq",
  x_vars_basename = c("gross_domestic_product_at_market_prices"),
  ardl_or_ecm = "ardl")

done_isat_modelling2 <- isat_modelling(clean_data = imports_data_clean, 
                                       dep_var_basename = "imports_of_goods_and_services",
                                       ardl_or_ecm = "ardl")





