#' Internal function to create the dictionaries
#' This script contains a separate function called generate_dictionary_script. This can be used to read in a modified dictionary and will then give out the code to insert into this function.
#' @param single_df Logical. If TRUE, the function will return a single data frame with all dictionaries. If FALSE, the function will return a list of data frames.
#'
#' @returns Either a list of dictionaries or a data.frame with a single dictionary.
create_dictionaries <- function(single_df = FALSE){

  # This script creates dictionaries for the different datasets used in the project.

  generate_dictionary_script <- function(data) {
    #, output_file = "generated_script.R") {
    # Ensure data is a tibble
    if (!is.data.frame(data)) {
      stop("Input data must be a tibble or data.frame.")
    }

    # Get column names
    col_names <- names(data)

    # Initialize the script
    script <- "library(tibble)\nlibrary(dplyr)\n\ndata_tibble <- tibble::tibble("

    # if there is a empty space in any of col_names, wrap that individual col_name in backticks
    col_names <- ifelse(grepl(" ", col_names), paste0("`", col_names, "`"), col_names)

    script <- paste0(script, paste(col_names, "= character()", collapse = ",\n  "), ") %>% \n")

    # Add rows using add_row()
    for (i in seq_len(nrow(data))) {
      row_values <- purrr::map_chr(data[i, ], ~ifelse(is.na(.x), "NA", paste0('"', .x, '"')))
      add_row_command <- paste0("  dplyr::add_row(", paste(col_names, "=", row_values, collapse = ", "), ")")
      script <- paste0(script, "  ", add_row_command, " %>% \n")
    }

    # Remove trailing pipe (%>%) from last row
    script <- gsub(" %>% \\n$", "\n", script)

    cat(script)

    # # Write script to file
    # writeLines(script, output_file)
    #
    # message("Script written to ", output_file)
  }


  # Identities --------------------------------------------------------------


  dict_identities <- dplyr::tibble(model_varname = character(),
                                   full_name = character(),
                                   variable_code = character()) %>%
    dplyr::add_row(model_varname = "Supply", full_name = "Total Supply", variable_code = NA) %>%
    dplyr::add_row(model_varname = "Demand", full_name = "Total Demand", variable_code = NA) %>%
    dplyr::add_row(model_varname = "GDPOutput", full_name = "GDP Output Approach", variable_code = NA) %>%
    dplyr::add_row(model_varname = "GDPExpenditure", full_name = "GDP Expenditure Approach", variable_code = NA) %>%
    dplyr::add_row(model_varname = "CO2Industry", full_name = "Co2 Emissions Industry in Tonnes", variable_code = NA) %>%
    dplyr::add_row(model_varname = "TOTS", full_name = "Total Supply", variable_code = "TOTS") %>%
    dplyr::add_row(model_varname = "DomDemand", full_name = "Domestic Demand", variable_code = "DomDemand")


  # EDGAR -------------------------------------------------------------------

  dict_edgar <- dplyr::tibble(
    ipcc_sector = character(),
    full_name = character(),
    model_varname = character(),
    dataset_id = character(),
    database = character(),
    geo = character(),
    freq = character()
  ) %>%
    # Energy Emissions
    dplyr::add_row(model_varname = "EmiCO2ElecHeat", ipcc_sector = "1.A.1.a", full_name = "CO2 Energy Emissions (fossil) from Main Activity Electricity and Heat Production", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2PetrRef", ipcc_sector = "1.A.1.bc", full_name = "CO2 Energy Emissions (fossil) from Petroleum Refining - Manufacture of Solid Fuels and Other Energy Industries", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2ManInd", ipcc_sector = "1.A.2", full_name = "CO2 Energy Emissions (fossil) from Manufacturing Industries and Construction", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2CivAvi", ipcc_sector = "1.A.3.a", full_name = "CO2 Energy Emissions (fossil) from Civil Aviation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2RoaTra", ipcc_sector = "1.A.3.b_noRES", full_name = "CO2 Energy Emissions (fossil) from Road Transportation no resuspension", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2Rail", ipcc_sector = "1.A.3.c", full_name = "CO2 Energy Emissions (fossil) from Railways", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2WatNav", ipcc_sector = "1.A.3.d", full_name = "CO2 Energy Emissions (fossil) from Water-borne Navigation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2OthTransp", ipcc_sector = "1.A.3.e", full_name = "CO2 Energy Emissions (fossil) from Other Transportation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2Residential", ipcc_sector = "1.A.4", full_name = "CO2 Energy Emissions (fossil) from Residential and other sectors", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2SolidFuel", ipcc_sector = "1.B.1", full_name = "CO2 Energy Emissions (fossil) from Solid Fuels", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2OilandGas", ipcc_sector = "1.B.2", full_name = "CO2 Energy Emissions (fossil) from Oil and Natural Gas", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%

    # Process Emissions
    dplyr::add_row(model_varname = "EmiCO2CemPro", ipcc_sector = "2.A.1", full_name = "CO2 Process Emissions (fossil) from Cement production", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2LimeProd", ipcc_sector = "2.A.2", full_name = "CO2 Process Emissions (fossil) from Lime production", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2GlassProd", ipcc_sector = "2.A.3", full_name = "CO2 Process Emissions (fossil) from Glass Production", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2OthCarb", ipcc_sector = "2.A.4", full_name = "CO2 Process Emissions (fossil) from Other Process Uses of Carbonates", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2ChemInd", ipcc_sector = "2.B", full_name = "CO2 Process Emissions (fossil) from Chemical Industry", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2MetalInd", ipcc_sector = "2.C", full_name = "CO2 Process Emissions (fossil) from Metal Industry", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2NonEnergProd", ipcc_sector = "2.D", full_name = "CO2 Process Emissions (fossil) from Non-Energy Products from Fuels and Solvent Use", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%

    # Agriculture Emissions
    dplyr::add_row(model_varname = "EmiCO2Liming", ipcc_sector = "3.C.2", full_name = "CO2 Emissions (fossil) from Liming", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2UreaApp", ipcc_sector = "3.C.3", full_name = "CO2 Emissions (fossil) from Urea application", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%

    # Waste Emissions
    dplyr::add_row(model_varname = "EmiCO2Waste", ipcc_sector = "4.C", full_name = "CO2 Emissions (fossil) from Incineration and Open Burning of Waste", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%

    # add aggregated measures of CO2
    dplyr::add_row(model_varname = "EmiCO2Combustion", ipcc_sector = "1.A", full_name = "CO2 Energy Emissions (fossil) from Fuel Combustion Activities (aggregated)", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCO2IndustryProcess", ipcc_sector = "2", full_name = "CO2 Process Emissions (fossil) from Industry (aggregated)", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/IEA_EDGAR_CO2_m_1970_2023.zip", freq = NA, geo = "DE") %>%

    dplyr::add_row(model_varname = "EmiN2OSoils", ipcc_sector = "3.C.4", full_name = "N20 Emissions (Direct) from managed soils", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_N2O_m_1970_2023.zip", freq = "m", geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiN2OManure_indirect", ipcc_sector = "3.C.6", full_name = "N2O Emissions (Indirect) from manure management", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_N2O_m_1970_2023.zip", freq = "m", geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4Livestock", ipcc_sector = "3.A", full_name = "CH4 Emissions from Livestock", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = "m", geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiN2OTotal", ipcc_sector = "TOTAL", full_name = "N2O Emissions Total", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_N2O_m_1970_2023.zip", freq = "m", geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4ElecHeat", ipcc_sector = "1.A.1.a", full_name = "CH4 Emissions from Main Activity Electricity and Heat Production", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4PetrRef", ipcc_sector = "1.A.1.bc", full_name = "CH4 Emissions from Petroleum Refining - Manufacture of Solid Fuels and Other Energy Industries", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4ManInd", ipcc_sector = "1.A.2", full_name = "CH4 Emissions from Manufacturing Industries and Construction", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4CivAvi", ipcc_sector = "1.A.3.a", full_name = "CH4 Emissions from Civil Aviation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4RoaTra", ipcc_sector =  "1.A.3.b_noRES", full_name = "CH4 Emissions from Road Transportation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4Rail", ipcc_sector = "1.A.3.c", full_name = "CH4 Emissions from Railways", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4WatNav", ipcc_sector = "1.A.3.d", full_name = "CH4 Emissions from Water-borne Navigation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4OthTransp", ipcc_sector = "1.A.3.e", full_name = "CH4 Emissions from Other Transportation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4Residential", ipcc_sector = "1.A.4", full_name = "CH4 Emissions from Residential and other sectors", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4SolidFuel", ipcc_sector = "1.B.1", full_name = "CH4 Emissions from Solid Fuels", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4OilandGas", ipcc_sector = "1.B.2", full_name = "CH4 Emissions from Oil and Natural Gas", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4ChemInd", ipcc_sector = "2.B", full_name = "CH4 Emissions from Chemical Industry", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4MetalInd", ipcc_sector = "2.C", full_name = "CH4 Emissions from Metal Industry", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4EntericFerment", ipcc_sector = "3.A.1", full_name = "CH4 Emissions from Enteric Fermentation", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4ManureMgmt", ipcc_sector = "3.A.2", full_name = "CH4 Emissions from Manure Management", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4BiomassBurn", ipcc_sector = "3.C.1", full_name = "CH4 Emissions from Biomass Burning", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4SolidWaste", ipcc_sector = "4.A", full_name = "CH4 Emissions from Solid Waste Disposal", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4BioWasteTreat", ipcc_sector = "4.B", full_name = "CH4 Emissions from Biological Treatment of Solid Waste", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4Waste", ipcc_sector = "4.C", full_name = "CH4 Emissions from Incineration and Open Burning of Waste", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%
    dplyr::add_row(model_varname = "EmiCH4Wastewater", ipcc_sector = "4.D", full_name = "CH4 Emissions from Wastewater Treatment and Discharge", database = "edgar", dataset_id = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/EDGAR_2024_GHG/EDGAR_CH4_m_1970_2023.zip", freq = NA, geo = "DE") %>%


    dplyr::mutate(freq = "m")



  # eurostat ----------------------------------------------------------------

  # create dictionary for Eurostat
  # generate_dictionary_script(dict_eurostat %>% janitor::remove_empty("cols"))

  dict_eurostat <- dplyr::tibble(model_varname = character(),
                                 full_name = character(),
                                 database = character(),
                                 variable_code = character(),
                                 dataset_id = character(),
                                 var_col = character(),
                                 freq = character(),
                                 geo = character(),
                                 unit = character(),
                                 s_adj = character(),
                                 nace_r2 = character(),
                                 cpa2_1 = character(),
                                 sector = character(),
                                 direct = character(),
                                 age = character(),
                                 partner = character(),
                                 finpos = character(),
                                 p_adj = character(),
                                 meat = character(),
                                 citizen = character(),
                                 wstatus = character(),
                                 tra_oper = character()) %>%
    dplyr::add_row(model_varname = "ATaxesA", full_name = "Product Taxes", database = "eurostat", variable_code = "D21", dataset_id = "nama_10_gdp", var_col = "na_item", freq = "a", geo = "DE", unit = "CP_MEUR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ASubsidiesA", full_name = "Product Subsidies", database = "eurostat", variable_code = "D31", dataset_id = "nama_10_gdp", var_col = "na_item", freq = "a", geo = "DE", unit = "CP_MEUR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Agriculture", full_name = "CO2 Emissions Agriculture in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "A", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Mining", full_name = "CO2 Emissions Mining and Quarrying in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "B", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Manufacturing", full_name = "CO2 Emissions Manufacturing in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "C", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Energy", full_name = "CO2 Emissions Electricity, Gas, Steam and Air Conditioning Supply in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "D", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Water", full_name = "CO2 Emissions Water Supply, Sewerage, Waste Management and Remediation Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Construction", full_name = "CO2 Emissions Construction in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Wholesale", full_name = "CO2 Emissions Wholesale and Retail Trade, Repair of Motor Vehicles and Motorcycles in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "G", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Transport", full_name = "CO2 Emissions Transportation and Storage in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "H", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Accommodation", full_name = "CO2 Emissions Accommodation and Food Service Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Information", full_name = "CO2 Emissions Information and Communication in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "J", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Finance", full_name = "CO2 Emissions Financial and Insurance Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "K", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2RealEstate", full_name = "CO2 Emissions Real Estate Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "L", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Science", full_name = "CO2 Emissions Professional, Scientific and Technical Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "M", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Support", full_name = "CO2 Emissions Administrative and Support Service Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Public", full_name = "CO2 Emissions Public Administration and Defence, Compulsory Social Security in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "O", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Education", full_name = "CO2 Emissions Education in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "P", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Health", full_name = "CO2 Emissions Human Health and Social Work Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "Q", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Arts", full_name = "CO2 Emissions Arts, Entertainment and Recreation in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "R", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Service", full_name = "CO2 Emissions Other Service Activities in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "S", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2HHEmployment", full_name = "CO2 Emissions Activities of Households as Employers, Undifferentiated Goods- and Services-Producing Activities of Households for Own Use in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "T", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2Extraterritorial", full_name = "CO2 Emissions Activities of Extraterritorial Organisations and Bodies in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "U", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CO2HH", full_name = "CO2 Emissions Total Activities by Households in Tonnes", database = "eurostat", variable_code = "CO2", dataset_id = "env_ac_ainah_r2", var_col = "airpol", freq = "a", geo = "DE", unit = "T", s_adj = NA, nace_r2 = "TOTAL_HH", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HouseWealthHH", full_name = "Household Dwellings Assets", database = "eurostat", variable_code = "N111N", dataset_id = "nama_10_nfa_bs", var_col = "asset10", freq = "a", geo = "DE", unit = "CP_MEUR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = "S14_S15", direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LandWealthHH", full_name = "Household Land Assets", database = "eurostat", variable_code = "N211N", dataset_id = "nama_10_nfa_bs", var_col = "asset10", freq = "a", geo = "DE", unit = "CP_MEUR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = "S14_S15", direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsAgric", full_name = "Exports of Agriculture, forestry and fishing", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "A", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsMining", full_name = "Exports of mining and quarrying", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "B", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsManufac", full_name = "Exports of manufacturing", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "C", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsElectricity", full_name = "Exports of electricity, gas, steam and air conditioning supply", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "D", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsWater", full_name = "Exports of Water supply; sewerage, waste management and remediation activites", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsConstruction", full_name = "Exports of construction", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsRetailMotor", full_name = "Exports of wholesale and retail trade; repair of motor vehicles and motor cycles", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "G", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsTransportStorage", full_name = "Exports of transportation and storage", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "H", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsAccomServices", full_name = "Exports of accomodation and services", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsInfoComms", full_name = "Exports of information and communication", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "J", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsFinnanceInsure", full_name = "Exports of finnance and insurance", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "K", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsRealestate", full_name = "Exports of Real estate activites", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "L", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsSci", full_name = "Exports of professional, scientific and technical activites", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "M", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsAdminSuport", full_name = "Exports of administrative and support service activites", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsAdminDefence", full_name = "Exports of public administrative and defence; compulsory social security", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "O", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsEducation", full_name = "Exports of education", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "P", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsHealth", full_name = "Exports of Human health", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "Q", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsArts", full_name = "Exports of Arts, entertainment and recreation", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "R", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsOther", full_name = "Exports of other services", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "S", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsHouseholdEmployeers", full_name = "Exports of activities of households as employers", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "T", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExportsExtraterritorial", full_name = "Exports of extraterritorial organizations and bodies", database = "eurostat", variable_code = "EXP", dataset_id = "ext_tec09", var_col = "stk_flow", freq = "a", geo = "DE", unit = "THS_EUR", s_adj = NA, nace_r2 = "U", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = "WORLD", finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsIndustry", full_name = "Wage costs for Industry except Construction", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "B-E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HoursWorkedPerEmployeeIndustry", full_name = "Hours worked per employed person for Industry except Construction", database = "eurostat", variable_code = "HW_EMP", dataset_id = "nama_10_lp_a21", var_col = "na_item", freq = "a", geo = "DE", unit = "HW", s_adj = NA, nace_r2 = "B-E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsGovArtsOther", full_name = "Wage costs Public administration and defence; compulsory social security; education; human health and social work activities; arts, entertainment and recreation; other service activities", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "O-S", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsArts", full_name = "Wage costs arts", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "R", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsOther", full_name = "Wage costs other services", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "S", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsWholesale", full_name = "Wage costs wholesale and retail trade", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "G", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsTransport", full_name = "Wage costs transport", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "H", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsAccommodation", full_name = "Wage costs food and accomodation", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HoursWorkedPerEmployeeRetail", full_name = "Hours worked per employed person for Retail", database = "eurostat", variable_code = "HW_EMP", dataset_id = "nama_10_lp_a21", var_col = "na_item", freq = "a", geo = "DE", unit = "HW", s_adj = NA, nace_r2 = "G-I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsRealEstate", full_name = "Wage costs real estate activities", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "L", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsScience", full_name = "Wage costs professional, scientific, techincal wage costs", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "M", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "WageCostsSupport", full_name = "Wage costs Admin and support services", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HoursWorkedPerEmployeeScience", full_name = "Hours worked per employed person for professionals", database = "eurostat", variable_code = "HW_EMP", dataset_id = "nama_10_lp_a21", var_col = "na_item", freq = "a", geo = "DE", unit = "HW", s_adj = NA, nace_r2 = "M", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HoursWorkedPerEmployeeSupport", full_name = "Hours worked per employed person for admin and support", database = "eurostat", variable_code = "HW_EMP", dataset_id = "nama_10_lp_a21", var_col = "na_item", freq = "a", geo = "DE", unit = "HW", s_adj = NA, nace_r2 = "N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabourCostsEconomy", full_name = "Economy wide labour cost industry, construction and services (except pub admin, defense, compulsory social security)", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "lc_lci_lev", var_col = "lcstruct", freq = "a", geo = "DE", unit = "EUR", s_adj = NA, nace_r2 = "B-S_X_O", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Taxes", full_name = "Product Taxes", database = "eurostat", variable_code = "D21REC", dataset_id = "gov_10q_ggnfa", var_col = "na_item", freq = "q", geo = "DE", unit = "MIO_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S13", direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Subsidies", full_name = "Product Subsidies", database = "eurostat", variable_code = "D31PAY", dataset_id = "gov_10q_ggnfa", var_col = "na_item", freq = "q", geo = "DE", unit = "MIO_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S13", direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAAgriculture", full_name = "Gross Value Added Agriculture", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "A", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAIndustry", full_name = "Gross Value Added Industry except Construction", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "B-E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAConstruction", full_name = "Gross Value Added Construction", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VARetail", full_name = "Gross Value Added Wholesail and Retail Trade, Transportation and Storage, Accommodation and Food Service Activities", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "G-I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAInformation", full_name = "Gross Value Added Information and Communication", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "J", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAFinance", full_name = "Gross Value Added Financial and Insurance Activities", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "K", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VARealEstate", full_name = "Gross Value Added Real Estate Services", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "L", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAService", full_name = "Gross Value Added Professional, Scientific, Technical, Administration and Support Service Activities", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "M_N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAGov", full_name = "Gross Value Added Public Administration, Defence, Education, Human Health and Social Work Activities", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "O-Q", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "VAOther", full_name = "Gross Value Added Other Services", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = "R-U", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ConsHH", full_name = "Household and NPISH Final Consumption Expenditure", database = "eurostat", variable_code = "P31_S14_S15", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ConsGov", full_name = "Government Final Consumption Expenditure", database = "eurostat", variable_code = "P3_S13", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Exports", full_name = "Exports of Goods and Services", database = "eurostat", variable_code = "P6", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Imports", full_name = "Imports of Goods and Services", database = "eurostat", variable_code = "P7", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "REER", full_name = "Real Effective Exchange Rate", database = "eurostat", variable_code = "REER_IC42_CPI", dataset_id = "ert_eff_ic_q", var_col = "exch_rt", freq = "q", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "IncomeHH", full_name = "Gross Disposable Income Households and Non-Profit Institutions Serving Households in Mio EUR", database = "eurostat", variable_code = "B6G", dataset_id = "nasq_10_nf_tr", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S14_S15", direct = "RECV", age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CapFormHH", full_name = "Gross Fixed Capital Formation Households", database = "eurostat", variable_code = "P51G", dataset_id = "nasq_10_nf_tr", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S14_S15", direct = "PAID", age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CapFormGov", full_name = "Gross Fixed Capital Formation Government", database = "eurostat", variable_code = "P51G", dataset_id = "nasq_10_nf_tr", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S13", direct = "PAID", age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CapFormFirm", full_name = "Gross Fixed Capital Non-Financial Corporations", database = "eurostat", variable_code = "P51G", dataset_id = "nasq_10_nf_tr", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S11", direct = "PAID", age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CapFormFinFirm", full_name = "Gross Fixed Capital Financial Corporations", database = "eurostat", variable_code = "P51G", dataset_id = "nasq_10_nf_tr", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = "S12", direct = "PAID", age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HousePriceIndex", full_name = "House Price Index", database = "eurostat", variable_code = "TOTAL", dataset_id = "prc_hpi_q", var_col = "purchase", freq = "q", geo = "DE", unit = "I15_Q", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "BuildingPermits", full_name = "New Residential Building Permits Square Metre Useful Floor Area", database = "eurostat", variable_code = "BPRM_SQM", dataset_id = "sts_cobp_q", var_col = "indic_bt", freq = "q", geo = "DE", unit = "I15", s_adj = "NSA", nace_r2 = NA, cpa2_1 = "CPA_F41001", sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAAgriculture", full_name = "Deflator VAAgriculture", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "A", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAIndustry", full_name = "Deflator VAIndustry", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "B-E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAConstruction", full_name = "Deflator VAConstruction", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVARetail", full_name = "Deflator VARetail", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "G-I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAInformation", full_name = "Deflator VAInformation", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "J", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAFinance", full_name = "Deflator VAFinance", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "K", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVARealEstate", full_name = "Deflator VARealEstate", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "L", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAService", full_name = "Deflator VAService", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "M_N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAGov", full_name = "Deflator VAGov", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "O-Q", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFVAOther", full_name = "Deflator VAOther", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = "R-U", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFExports", full_name = "DF Exports", database = "eurostat", variable_code = "P6", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFImports", full_name = "DF Imports", database = "eurostat", variable_code = "P7", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFTaxesLessSubsidies", full_name = "Deflator TaxesLessSubsidies", database = "eurostat", variable_code = "D21X31", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFConsHH", full_name = "Deflator ConsHH", database = "eurostat", variable_code = "P31_S14_S15", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFCapForm", full_name = "Deflator CapForm", database = "eurostat", variable_code = "P51G", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "DFGDP", full_name = "Deflator GDP", database = "eurostat", variable_code = "B1GQ", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD15_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "URate", full_name = "Total Unemployment Rate Labour Force", database = "eurostat", variable_code = "T", dataset_id = "une_rt_q", var_col = "sex", freq = "q", geo = "DE", unit = "PC_ACT", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = "Y15-74", partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabourProd", full_name = "Real Labour Productivity per Person", database = "eurostat", variable_code = "RLPR_PER", dataset_id = "namq_10_lp_ulc", var_col = "na_item", freq = "q", geo = "DE", unit = "I15", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "EfExchange", full_name = "Effective Exchange Rate", database = "eurostat", variable_code = "NEER_IC42", dataset_id = "ert_eff_ic_q", var_col = "exch_rt", freq = "q", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabourCI", full_name = "Labour Cost Index", database = "eurostat", variable_code = "D1_D4_MD5", dataset_id = "teilm140", var_col = "lcstruct", freq = "q", geo = "DE", unit = "I20", s_adj = "SCA", nace_r2 = "B-S", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "TaxesLessSubsidies", full_name = "Product Taxes Less Product Subsidies", database = "eurostat", variable_code = "D21X31", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "FinWealthHH", full_name = "Household Financial Net Worth in Mio EUR", database = "eurostat", variable_code = "BF90", dataset_id = "nasq_10_f_bs", var_col = "na_item", freq = "q", geo = "DE", unit = "MIO_EUR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = "S14_S15", direct = NA, age = NA, partner = NA, finpos = "LIAB", p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "MetalProd", full_name = "Index of Manufacture of basic metals and fabricated metal products", database = "eurostat", variable_code = "PROD", dataset_id = "sts_inpr_q", var_col = "indic_bt", freq = "q", geo = NA, unit = "I15", s_adj = "NSA", nace_r2 = "C24_C25", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "PlasticProd", full_name = "Index of Plastic Production", database = "eurostat", variable_code = "PROD", dataset_id = "sts_inpr_q", var_col = "indic_bt", freq = "q", geo = NA, unit = "I15", s_adj = "NSA", nace_r2 = "C222", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Price_AgriProducts", full_name = "Price indices of agricultural products, output", database = "eurostat", variable_code = "140000", dataset_id = "apri_pi20_outq", var_col = "product", freq = "q", geo = "DE", unit = "I20", s_adj = "NSA", nace_r2 = "B-D", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Price_AnimalProducts", full_name = "Price indices of agricultural products - Agricultural goods output", database = "eurostat", variable_code = "140000", dataset_id = "apri_pi15_outq", var_col = "product", freq = "q", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = "NI", meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Flights", full_name = "National air passenger transport by reporting country", database = "eurostat", variable_code = "CAF_PAS", dataset_id = "avia_panc", var_col = "tra_meas", freq = "m", geo = "DE", unit = "FLIGHT", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ConstructionManuf", full_name = "Production in Construction in Manufacturing Sectors", database = "eurostat", variable_code = "PRD", dataset_id = "sts_copr_m", var_col = "indic_bt", freq = "m", geo = "DE", unit = "I21", s_adj = "NSA", nace_r2 = "B-D_F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ConstructionBuildings", full_name = "Production in Construction in the Building sector", database = "eurostat", variable_code = "PROD", dataset_id = "sts_copr_m", var_col = "indic_bt", freq = "m", geo = "DE", unit = "I21", s_adj = "NSA", nace_r2 = "F41", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Lab_Inp_Constr", full_name = "Labour input in construction", database = "eurostat", variable_code = "EMPL", dataset_id = "sts_colb_m", var_col = "indic_bt", freq = "m", geo = "DE", unit = "I21", s_adj = "NSA", nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Lab_Inp_Indus", full_name = "Labour input in industry", database = "eurostat", variable_code = "EMPL", dataset_id = "sts_inlb_m", var_col = "indic_bt", freq = "m", geo = "DE", unit = "I21", s_adj = "NSA", nace_r2 = "B-E36", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ElectrCons", full_name = "Consumption of electricity - GWh", database = "eurostat", variable_code = "IS-CEL-GWH", dataset_id = "ei_isen_m", var_col = "indic", freq = "m", geo = "DE", unit = NA, s_adj = "NSA", nace_r2 = "B-D", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "AnimalImports", full_name = "Total imports of live animals", database = "eurostat", variable_code = "SL", dataset_id = "apro_mt_pheadm", var_col = "meatitem", freq = "m", geo = "DE", unit = "THS_T", s_adj = "NSA", nace_r2 = "B-D", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = "B1000", citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "TurnoverInd", full_name = "Turnover in industry, domestic market - monthly data", database = "eurostat", variable_code = "TOVD", dataset_id = "sts_intvd_m", var_col = "indic_bt", freq = "m", geo = "DE", unit = "I21", s_adj = "NSA", nace_r2 = "B_C", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "PPI", full_name = "Output prices of the domestic market index (Producer price index) (NSA)", database = "eurostat", variable_code = "IS-PPI", dataset_id = "ei_isir_m", var_col = "indic", freq = "m", geo = "DE", unit = "RT1", s_adj = "NSA", nace_r2 = "B-E36", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Unemp", full_name = "Unemployment", database = "eurostat", variable_code = "T", dataset_id = "lfsq_urgan", var_col = "sex", freq = "q", geo = "DE", unit = "PC", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = "Y20-64", partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = "TOTAL", wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "EmpCompensation", full_name = "Compensation of employees", database = "eurostat", variable_code = "D1", dataset_id = "tipslm14", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MNAC", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "ExchangeRate", full_name = "Nominal effective exchange rate - 42 trading partners (industrial countries)", database = "eurostat", variable_code = "NEER_IC42", dataset_id = "ert_eff_ic_q", var_col = "exch_rt", freq = "q", geo = "DE", unit = "I15", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GDP_Deflator", full_name = "GDP deflator", database = "eurostat", variable_code = "B1GQ", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "PD10_EUR", s_adj = "NSA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GDP", full_name = "Gross domestic product at market prices", database = "eurostat", variable_code = "B1GQ", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAdd", full_name = "Value added, gross", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "TOTAL", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Export", full_name = "Exports of goods and services", database = "eurostat", variable_code = "P6", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Import", full_name = "Imports of goods and services", database = "eurostat", variable_code = "P7", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GCapitalForm", full_name = "Gross capital formation", database = "eurostat", variable_code = "P5G", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "FinConsExp", full_name = "Final consumption expenditure", database = "eurostat", variable_code = "P3", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "FinConsExpGov", full_name = "Final consumption expenditure of general government", database = "eurostat", variable_code = "P3_S13", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "FinConsExpHH", full_name = "Household and NPISH final consumption expenditure", database = "eurostat", variable_code = "P31_S14_S15", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "StatDiscrep", full_name = "Statistical discrepancy (expenditure approach)", database = "eurostat", variable_code = "YA0", dataset_id = "namq_10_gdp", var_col = "na_item", freq = "q", geo = "DE", unit = "CP_MEUR", s_adj = "SCA", nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "Emissions", full_name = "Greenhouse Gas Emissions (All NACE and HH)", database = "eurostat", variable_code = "GHG", dataset_id = "env_ac_aigg_q", var_col = "airpol", freq = "q", geo = "DE", unit = "THS_T", s_adj = "SCA", nace_r2 = "TOTAL_HH", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabCostManuf", full_name = "Manufacturing Labour cost index - Total Labour Cost", database = "eurostat", variable_code = "LM-LCI-TOT", dataset_id = "ei_lmlc_q", var_col = "indic", freq = "q", geo = "DE", unit = "I20", s_adj = "SCA", nace_r2 = "C", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddManuf", full_name = "Value added, gross Manufacturing", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "C", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddGov", full_name = "Value added, gross Government", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "O-Q", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabCostConstr", full_name = "Construction Labour cost index - Total Labour Cost", database = "eurostat", variable_code = "LM-LCI-TOT", dataset_id = "ei_lmlc_q", var_col = "indic", freq = "q", geo = "DE", unit = "I20", s_adj = "SCA", nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabCostService", full_name = "Service Labour cost index - Total Labour Cost", database = "eurostat", variable_code = "LM-LCI-TOT", dataset_id = "ei_lmlc_q", var_col = "indic", freq = "q", geo = "DE", unit = "I20", s_adj = "SCA", nace_r2 = "G-N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddConstr", full_name = "Value added, gross Construction", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "F", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddAgri", full_name = "Value added, gross Agriculture", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "A", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddIndus", full_name = "Value added, gross Industry", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "B-E", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddInfocom", full_name = "Value added, gross Information and Communication", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "J", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddFinance", full_name = "Value added, gross Financial Services", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "K", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddRealest", full_name = "Value added, gross Real Estate", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "L", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddResearch", full_name = "Value added, gross Scientific and Professional Services", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "M_N", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddArts", full_name = "Value added, gross Arts and Entertainment", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "R-U", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "GValueAddWholesaletrade", full_name = "Value added, gross Wholesale and retail trade and Tourism", database = "eurostat", variable_code = "B1G", dataset_id = "namq_10_a10", var_col = "na_item", freq = "q", geo = "DE", unit = "CLV05_MEUR", s_adj = "SCA", nace_r2 = "G-I", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP", full_name = "Harmonised Index of Consumer Prices, all items, index 100 = 2015", database = "eurostat", variable_code = "CP00", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Energy", full_name = "Harmonised Index of Consumer Prices, Energy, index 100 = 2015", database = "eurostat", variable_code = "NRG", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Electricity", full_name = "Harmonised Index of Consumer Prices, Electricity, index 100 = 2015", database = "eurostat", variable_code = "CP0451", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Gas", full_name = "Harmonised Index of Consumer Prices, Gas, index 100 = 2015", database = "eurostat", variable_code = "CP0452", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Liquid_Fuels", full_name = "Harmonised Index of Consumer Prices, Liquid Fuels, index 100 = 2015", database = "eurostat", variable_code = "CP0453", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Solid_Fuels", full_name = "Harmonised Index of Consumer Prices, Solid Fuels, index 100 = 2015", database = "eurostat", variable_code = "CP0454", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Heat", full_name = "Harmonised Index of Consumer Prices, Heat Energy, index 100 = 2015", database = "eurostat", variable_code = "CP0455", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HDD", full_name = "Heating Degree Days", database = "eurostat", variable_code = "HDD", dataset_id = "nrg_chdd_m", var_col = "indic_nrg", freq = "m", geo = "DE", unit = "NR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "CDD", full_name = "Cooling Degree Days", database = "eurostat", variable_code = "CDD", dataset_id = "nrg_chdd_m", var_col = "indic_nrg", freq = "m", geo = "DE", unit = "NR", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "IndProd", full_name = "An index of Industrial Production", database = "eurostat", variable_code = "PRD", dataset_id = "sts_inpr_q", var_col = "indic_bt", freq = "q", geo = "DE", unit = "I15", s_adj = "NSA", nace_r2 = "B-D", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "PT_Emp", full_name = "Part-time employment and temporary contracts", database = "eurostat", variable_code = "T", dataset_id = "lfsi_pt_q", var_col = "sex", freq = "q", geo = "DE", unit = "PC_EMP", s_adj = "NSA", nace_r2 = "", cpa2_1 = NA, sector = NA, direct = NA, age = "Y20-64", partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = "EMP_PT", tra_oper = NA) %>%
    dplyr::add_row(model_varname = "LabCost_ICS", full_name = "labour cost index in Industry, construction and services", database = "eurostat", variable_code = "LM-LCI-TOT", dataset_id = "ei_lmlc_q", var_col = "indic", freq = "q", geo = "DE", unit = "I20", s_adj = "NSA", nace_r2 = "B-S", cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Diesel", full_name = "Harmonised Price Index for Diesel", database = "eurostat", variable_code = "CP07221", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_Petrol", full_name = "Harmonised Price Index for Petrol", database = "eurostat", variable_code = "CP07222", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_FlightsDom", full_name = "Harmonised Price Index for Domestic flights", database = "eurostat", variable_code = "CP07331", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "HICP_AviaInt", full_name = "Harmonised Price Index for International flights", database = "eurostat", variable_code = "CP07332", dataset_id = "prc_hicp_midx", var_col = "coicop", freq = "m", geo = "DE", unit = "I15", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = NA) %>%
    dplyr::add_row(model_varname = "RoadFreight", full_name = "Road freight transport", database = "eurostat", variable_code = "TOTAL", dataset_id = "road_go_tq_tott", var_col = "tra_type", freq = "q", geo = "DE", unit = "MIO_TKM", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = NA, citizen = NA, wstatus = NA, tra_oper = "TOTAL") %>%
    dplyr::add_row(model_varname = "Slaughter", full_name = "Slaughterings", database = "eurostat", variable_code = "SL", dataset_id = "apro_mt_pwgtm", var_col = "meatitem", freq = "m", geo = "DE", unit = "THS_T", s_adj = NA, nace_r2 = NA, cpa2_1 = NA, sector = NA, direct = NA, age = NA, partner = NA, finpos = NA, p_adj = NA, meat = "B1000", citizen = NA, wstatus = NA, tra_oper = NA)



  # StatCan -----------------------------------------------------------------

  # generate_dictionary_script(dict_statcan %>% janitor::remove_empty("cols"))

  dict_statcan <- dplyr::tibble(model_varname = character(),
                                full_name = character(),
                                database = character(),
                                dataset_id = character(),
                                freq = character(),
                                GEO = character(),
                                `Seasonal adjustment` = character(),
                                `North American Industry Classification System (NAICS)` = character(),
                                `North American Product Classification System (NAPCS)` = character(),
                                Prices = character(),
                                `Type of fuel` = character(),
                                `Products and product groups` = character()) %>%
    dplyr::add_row(model_varname = "Gasoline_price", full_name = "Monthly Average Retail Price for Gasoline (regular unleaded) in centrs per liter", database = "statcan", dataset_id = "18-10-0001-01", freq = "m", GEO = "Canada", `Seasonal adjustment` = NA, `North American Industry Classification System (NAICS)` = NA, `North American Product Classification System (NAPCS)` = NA, Prices = NA, `Type of fuel` = "Regular unleaded gasoline at self service filling stations", `Products and product groups` = NA) %>%
    dplyr::add_row(model_varname = "CPI_Energy", full_name = "Consumer Price Index, monthly, not seasonally adjusted, Energy, index 100 = 2002", database = "statcan", dataset_id = "18-10-0004-01", freq = "m", GEO = "Canada", `Seasonal adjustment` = NA, `North American Industry Classification System (NAICS)` = NA, `North American Product Classification System (NAPCS)` = NA, Prices = NA, `Type of fuel` = NA, `Products and product groups` = "Energy") %>%
    dplyr::add_row(model_varname = "CPI_Gasoline", full_name = "Consumer Price Index, monthly, not seasonally adjusted, Gasoline, index 100 = 2002", database = "statcan", dataset_id = "18-10-0004-01", freq = "m", GEO = "Canada", `Seasonal adjustment` = NA, `North American Industry Classification System (NAICS)` = NA, `North American Product Classification System (NAPCS)` = NA, Prices = NA, `Type of fuel` = NA, `Products and product groups` = "Gasoline") %>%
    dplyr::add_row(model_varname = "IndProdPriceIndex", full_name = "Total, Industrial product price index (IPPI)", database = "statcan", dataset_id = "18-10-0266-01", freq = "m", GEO = "Canada", `Seasonal adjustment` = NA, `North American Industry Classification System (NAICS)` = NA, `North American Product Classification System (NAPCS)` = "Total, Industrial product price index (IPPI)", Prices = NA, `Type of fuel` = NA, `Products and product groups` = NA) %>%
    dplyr::add_row(model_varname = "IndProdGDP", full_name = "Industrial production [T010] in 2017 constant prices", database = "statcan", dataset_id = "36-10-0434-01", freq = "m", GEO = "Canada", `Seasonal adjustment` = "Seasonally adjusted at annual rates", `North American Industry Classification System (NAICS)` = "Industrial production [T010]", `North American Product Classification System (NAPCS)` = NA, Prices = "2017 constant prices", `Type of fuel` = NA, `Products and product groups` = NA)

  # IMF ---------------------------------------------------------------------

  # generate_dictionary_script(dict_imf %>% janitor::remove_empty("cols"))

  dict_imf <- dplyr::tibble(model_varname = character(),
                            full_name = character(),
                            database = character(),
                            dataset_id = character(),
                            freq = character(),
                            ref_area = character(),
                            commodity = character(),
                            unit_measure = character()) %>%
    dplyr::add_row(model_varname = "WORLD_OIL", full_name = "World Oil Price USD", database = "imf", dataset_id = "PCPS", freq = "M", ref_area = "W00", commodity = "POILAPSP", unit_measure = "USD")


  # Output ------------------------------------------------------------------

  out <- list()
  out$dict_identities <- dict_identities
  out$dict_eurostat <- dict_eurostat
  out$dict_edgar <- dict_edgar
  out$dict_statcan <- dict_statcan
  out$dict_imf <- dict_imf

  if(single_df){
    out <- dplyr::bind_rows(out)
  }

  return(out)

  # # when finished run usethis::use_data()
  # dicts <- create_dictionaries()
  #
  # dict_identities <- dicts$dict_identities
  # usethis::use_data(dict_identities, overwrite = TRUE)
  #
  # dict_eurostat <- dicts$dict_eurostat
  # usethis::use_data(dict_eurostat, overwrite = TRUE)
  #
  # dict_edgar <- dicts$dict_edgar
  # usethis::use_data(dict_edgar, overwrite = TRUE)
  #
  # dict_statcan <- dicts$dict_statcan
  # usethis::use_data(dict_statcan, overwrite = TRUE)
  #
  # dict_imf <- dicts$dict_imf
  # usethis::use_data(dict_imf, overwrite = TRUE)

  # Create the overall dict
  # dict <- create_dictionaries(single_df = TRUE)
  # usethis::use_data(dict, overwrite = TRUE)

}

